DEFAULT_FEATURE_COUNT = 1500
DEFAULT_GOOD_MATCH_PERCENT = 0.2
DEFAULT_RANSAC_THRESH = 5.0
DEFAULT_OPACITY = 1.0
DEFAULT_MIN_MATCHES = 4
DEFAULT_MIN_INLIERS = 4
MATCHER_TYPES = ["orb", "akaze", "sift"]
