"""3D LUT fitting and .cube serialization for color matching."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import torch

def _lut_grid_colors(size: int, device: torch.device, dtype: torch.dtype) -> torch.Tensor:
    """Create flattened LUT input colors in .cube order (R fastest)."""
    levels = torch.linspace(0.0, 1.0, steps=size, device=device, dtype=dtype)
    bb, gg, rr = torch.meshgrid(levels, levels, levels, indexing="ij")
    return torch.stack([rr, gg, bb], dim=-1).reshape(-1, 3)


def _poly2_features(colors: torch.Tensor) -> torch.Tensor:
    """Build second-order polynomial RGB features for LUT baking."""
    r = colors[:, 0:1]
    g = colors[:, 1:2]
    b = colors[:, 2:3]
    ones = torch.ones_like(r)
    return torch.cat([ones, r, g, b, r * r, g * g, b * b, r * g, r * b, g * b], dim=1)


def _fit_poly2_color_map(
    src: torch.Tensor, dst: torch.Tensor, mask: Optional[torch.Tensor], max_samples: int = 50000
) -> torch.Tensor:
    """Fit polynomial RGB map from src->dst colors for LUT baking."""
    src_flat = src.reshape(-1, 3)
    dst_flat = dst.reshape(-1, 3)
    if mask is not None:
        keep = (mask > 0.5).reshape(-1)
        if int(keep.sum().item()) >= 10:
            src_flat = src_flat[keep]
            dst_flat = dst_flat[keep]
    if src_flat.shape[0] > max_samples:
        idx = torch.randperm(src_flat.shape[0], device=src.device)[:max_samples]
        src_flat = src_flat[idx]
        dst_flat = dst_flat[idx]
    x = _poly2_features(src_flat.float())
    y = dst_flat.float()
    xtx = x.t().matmul(x)
    xty = x.t().matmul(y)
    ridge = torch.eye(xtx.shape[0], device=x.device, dtype=x.dtype) * 1e-4
    beta = torch.linalg.solve(xtx + ridge, xty)
    return beta


def _apply_poly2_color_map(colors: torch.Tensor, beta: torch.Tensor) -> torch.Tensor:
    """Apply fitted polynomial RGB map to flattened LUT colors."""
    x = _poly2_features(colors.float())
    out = x.matmul(beta).to(dtype=colors.dtype)
    return torch.clamp(out, 0.0, 1.0)


def _sanitize_lut_name(name: str) -> str:
    """Sanitize LUT filename base."""
    base = (name or "").strip()
    if not base:
        return "color_match_lut"
    safe = "".join(ch if (ch.isalnum() or ch in ("-", "_")) else "_" for ch in base)
    return safe.strip("_") or "color_match_lut"


def _write_cube_file(path: Path, colors: torch.Tensor, size: int, title: str):
    """Write LUT colors to .cube file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by ComfyUI_ALEXZ_tools Color Match To Reference",
        f'TITLE "{title}"',
        f"LUT_3D_SIZE {int(size)}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
    ]
    flat = colors.detach().cpu().float().numpy()
    for r, g, b in flat:
        lines.append(f"{float(r):.6f} {float(g):.6f} {float(b):.6f}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
