"""JSON, UI schema, and identity LUT contracts for Look Match nodes."""

from __future__ import annotations

import json
from typing import Any

def _identity_cube_text(size: int) -> str:
    """Build identity LUT in .cube text format."""
    n = max(2, int(size))
    lines = [
        "# Generated by ALEXZ_tools Look Match Phase A",
        f"LUT_3D_SIZE {n}",
    ]
    for b in range(n):
        for g in range(n):
            for r in range(n):
                rr = r / float(n - 1)
                gg = g / float(n - 1)
                bb = b / float(n - 1)
                lines.append(f"{rr:.6f} {gg:.6f} {bb:.6f}")
    return "\n".join(lines) + "\n"


def _safe_json_loads(text: Any) -> dict:
    """Parse JSON object from arbitrary STRING input."""
    if isinstance(text, (list, tuple)):
        if not text:
            return {}
        text = text[0]
    if isinstance(text, bytes):
        text = text.decode("utf-8", errors="ignore")
    if not isinstance(text, str):
        return {}
    try:
        data = json.loads(text)
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}


def _build_resolve_input_types() -> dict:
    """Return INPUT_TYPES schema for resolve-style look match node."""
    return {
        "required": {
            "reference": ("IMAGE", {"tooltip": "Референс-изображение (целевой look)."}),
            "image": ("IMAGE", {"tooltip": "Изображение для color/look match."}),
            "strength": (
                "FLOAT",
                {"default": 1.0, "min": 0.0, "max": 1.0, "step": 0.05, "tooltip": "Сила применения итогового look (0..1)."},
            ),
        },
        "optional": {
            "compute_device": (
                ["auto", "cpu", "cuda"],
                {"default": "auto", "tooltip": "Устройство вычислений: auto/cpu/cuda."},
            ),
            "working_space": (
                ["oklab", "lab"],
                {"default": "oklab", "tooltip": "Рабочее цветовое пространство для fit/diagnostics."},
            ),
            "downscale_long_side": (
                ["as_is", "1440p", "1080p", "720p"],
                {"default": "1080p", "tooltip": "Размер для fit-этапов (без апскейла)."},
            ),
            "tone_model": (
                ["monotonic_spline", "gamma_gain_lift"],
                {"default": "monotonic_spline", "tooltip": "Модель подгонки тонального профиля."},
            ),
            "palette_model": (
                ["lut3d", "rbf"],
                {"default": "lut3d", "tooltip": "Модель палитрового переноса: affine(lut3d) или mean/std(rbf)."},
            ),
            "lut_size": (
                "INT",
                {"default": 25, "min": 17, "max": 49, "step": 2, "tooltip": "Размер экспортируемого 3D LUT."},
            ),
            "w_exposure": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 5.0, "step": 0.05, "tooltip": "Вес этапа exposure/WB."}),
            "w_tone": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 5.0, "step": 0.05, "tooltip": "Вес этапа tone matching."}),
            "w_chroma": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 5.0, "step": 0.05, "tooltip": "Вес этапа chroma/palette matching."}),
            "skin_protection": ("BOOLEAN", {"default": True, "tooltip": "Защита оттенков кожи (Phase A: контракт)."}),
            "skin_protection_strength": (
                "FLOAT",
                {"default": 0.6, "min": 0.0, "max": 1.0, "step": 0.05, "tooltip": "Сила защиты skin-tones."},
            ),
            "auto_fallback_cdf": (
                "BOOLEAN",
                {
                    "default": True,
                    "tooltip": "Авто-фоллбек: пробовать CDF/linear (+soft) и выбирать лучший результат по look-метрике с учетом тональной жесткости.",
                },
            ),
            "subject_mask": ("MASK", {"tooltip": "Опциональная маска объекта (Phase A: контракт)."}),
            "sky_mask": ("MASK", {"tooltip": "Опциональная маска неба."}),
            "ground_mask": ("MASK", {"tooltip": "Опциональная маска земли/фона."}),
            "export_lut_cube": ("BOOLEAN", {"default": False, "tooltip": "Запечь текущий resolve-look в .cube текст."}),
        },
    }


def _build_nuke_build_input_types() -> dict:
    """Return INPUT_TYPES schema for Nuke-style model builder."""
    return {
        "required": {
            "reference": ("IMAGE", {"tooltip": "Референс кадр (target look)."}),
            "source": ("IMAGE", {"tooltip": "Исходный кадр, относительно которого строится look-модель."}),
        },
        "optional": {
            "compute_device": (
                ["auto", "cpu", "cuda"],
                {"default": "auto", "tooltip": "Устройство вычислений: auto/cpu/cuda."},
            ),
            "working_space": (
                ["oklab", "lab"],
                {"default": "oklab", "tooltip": "Рабочее пространство fit-процесса."},
            ),
            "downscale_long_side": (
                ["as_is", "1440p", "1080p", "720p"],
                {"default": "1080p", "tooltip": "Размер fit-процесса (Phase A: контракт)."},
            ),
            "fit_global": ("BOOLEAN", {"default": True, "tooltip": "Фит глобального grade (Phase A: контракт)."}),
            "fit_tone": ("BOOLEAN", {"default": True, "tooltip": "Фит тонального профиля (Phase A: контракт)."}),
            "fit_hue_sectors": ("BOOLEAN", {"default": True, "tooltip": "Фит по hue-секторам (Phase A: контракт)."}),
            "fit_local_regions": ("BOOLEAN", {"default": True, "tooltip": "Фит локальных регионов по маскам (Phase A: контракт)."}),
            "skin_mask": ("MASK", {"tooltip": "Опциональная маска кожи."}),
            "sky_mask": ("MASK", {"tooltip": "Опциональная маска неба."}),
            "ground_mask": ("MASK", {"tooltip": "Опциональная маска земли/фона."}),
            "subject_mask": ("MASK", {"tooltip": "Опциональная маска объекта."}),
            "export_lut_cube": ("BOOLEAN", {"default": False, "tooltip": "Выдать identity .cube (Phase A)."}),
            "lut_size": ("INT", {"default": 25, "min": 17, "max": 49, "step": 2, "tooltip": "Размер экспортируемого LUT."}),
        },
    }


def _build_nuke_apply_input_types() -> dict:
    """Return INPUT_TYPES schema for Nuke-style model applier."""
    return {
        "required": {
            "image": ("IMAGE", {"tooltip": "Изображение/батч для применения look-модели."}),
            "look_model_json": ("STRING", {"tooltip": "JSON-модель из ImageLookMatchNukeBuild."}),
            "strength": (
                "FLOAT",
                {"default": 1.0, "min": 0.0, "max": 1.0, "step": 0.05, "tooltip": "Сила применения модели (0..1)."},
            ),
        },
        "optional": {
            "compute_device": (
                ["auto", "cpu", "cuda"],
                {"default": "auto", "tooltip": "Устройство вычислений: auto/cpu/cuda."},
            ),
            "temporal_stabilization": (
                "BOOLEAN",
                {"default": False, "tooltip": "Темпоральная стабилизация параметров (Phase A: контракт)."},
            ),
            "temporal_alpha": (
                "FLOAT",
                {"default": 0.8, "min": 0.0, "max": 1.0, "step": 0.05, "tooltip": "Коэффициент EMA для temporal режима."},
            ),
            "shot_change_threshold": (
                "FLOAT",
                {"default": 0.2, "min": 0.0, "max": 1.0, "step": 0.01, "tooltip": "Порог обнаружения резкого shot change."},
            ),
        },
    }
