"""
Module: nodes/image_look_match.py
Author: AlexZ1967
Last updated: 2026-02-18

Description:
    Contract-first Look Match nodes for strong-reference scenarios.

Purpose:
    Introduces Phase A interfaces for Resolve-style and Nuke-style look
    pipelines with stable JSON schemas and safe identity-grade behavior.
"""

from __future__ import annotations

import json
from typing import Any

import torch
from tqdm import tqdm

from ..utils import color_match_utils
from ..utils.interrupt import check_interrupt

_LOOK_RESOLVE_SCHEMA = "alexz.look_match.resolve"
_LOOK_MODEL_SCHEMA = "alexz.look_model.nuke_build"
_LOOK_APPLY_SCHEMA = "alexz.look_apply.nuke_apply"
_SCHEMA_VERSION = 1


def _pad_batch_last(batch: torch.Tensor, batch_size: int) -> torch.Tensor:
    """Pad tensor batch by repeating last item until `batch_size`."""
    return color_match_utils.pad_batch_last(batch, batch_size)


def _resolve_compute_device(requested: str) -> tuple[torch.device, str | None]:
    """Resolve requested compute device and return optional warning code."""
    req = str(requested).lower()
    if req == "cuda":
        if torch.cuda.is_available():
            return torch.device("cuda"), None
        return torch.device("cpu"), "cuda_requested_but_unavailable"
    if req == "cpu":
        return torch.device("cpu"), None
    if torch.cuda.is_available():
        return torch.device("cuda"), None
    return torch.device("cpu"), None


def _split_alpha(image_batch: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor | None]:
    """Split RGB and alpha channels from BHWC image batch."""
    if image_batch.shape[-1] > 3:
        return image_batch[..., :3], image_batch[..., 3:4]
    return image_batch, None


def _identity_cube_text(size: int) -> str:
    """Build identity LUT in .cube text format."""
    n = max(2, int(size))
    lines = [
        "# Generated by ALEXZ_tools Look Match Phase A",
        f"LUT_3D_SIZE {n}",
    ]
    for b in range(n):
        for g in range(n):
            for r in range(n):
                rr = r / float(n - 1)
                gg = g / float(n - 1)
                bb = b / float(n - 1)
                lines.append(f"{rr:.6f} {gg:.6f} {bb:.6f}")
    return "\n".join(lines) + "\n"


def _safe_json_loads(text: Any) -> dict:
    """Parse JSON object from arbitrary STRING input."""
    if isinstance(text, (list, tuple)):
        if not text:
            return {}
        text = text[0]
    if isinstance(text, bytes):
        text = text.decode("utf-8", errors="ignore")
    if not isinstance(text, str):
        return {}
    try:
        data = json.loads(text)
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}


def _build_resolve_input_types() -> dict:
    """Return INPUT_TYPES schema for resolve-style look match node."""
    return {
        "required": {
            "reference": ("IMAGE", {"tooltip": "Референс-изображение (целевой look)."}),
            "image": ("IMAGE", {"tooltip": "Изображение для color/look match."}),
            "strength": (
                "FLOAT",
                {"default": 1.0, "min": 0.0, "max": 1.0, "step": 0.05, "tooltip": "Сила применения итогового look (0..1)."},
            ),
        },
        "optional": {
            "compute_device": (
                ["auto", "cpu", "cuda"],
                {"default": "auto", "tooltip": "Устройство вычислений: auto/cpu/cuda."},
            ),
            "working_space": (
                ["oklab", "lab"],
                {"default": "oklab", "tooltip": "Рабочее цветовое пространство для fit/diagnostics."},
            ),
            "downscale_long_side": (
                ["as_is", "1440p", "1080p", "720p"],
                {"default": "1080p", "tooltip": "Размер внутренней оптимизации (Phase A: контрактный параметр)."},
            ),
            "tone_model": (
                ["monotonic_spline", "gamma_gain_lift"],
                {"default": "monotonic_spline", "tooltip": "Модель подгонки тонального профиля."},
            ),
            "palette_model": (
                ["lut3d", "rbf"],
                {"default": "lut3d", "tooltip": "Модель палитрового переноса (Phase A: контракт)."},
            ),
            "lut_size": (
                "INT",
                {"default": 25, "min": 17, "max": 49, "step": 2, "tooltip": "Размер экспортируемого 3D LUT."},
            ),
            "w_exposure": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 5.0, "step": 0.05, "tooltip": "Вес этапа exposure/WB."}),
            "w_tone": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 5.0, "step": 0.05, "tooltip": "Вес этапа tone matching."}),
            "w_chroma": ("FLOAT", {"default": 1.0, "min": 0.0, "max": 5.0, "step": 0.05, "tooltip": "Вес этапа chroma/palette matching."}),
            "skin_protection": ("BOOLEAN", {"default": True, "tooltip": "Защита оттенков кожи (Phase A: контракт)."}),
            "skin_protection_strength": (
                "FLOAT",
                {"default": 0.6, "min": 0.0, "max": 1.0, "step": 0.05, "tooltip": "Сила защиты skin-tones."},
            ),
            "subject_mask": ("MASK", {"tooltip": "Опциональная маска объекта (Phase A: контракт)."}),
            "sky_mask": ("MASK", {"tooltip": "Опциональная маска неба (Phase A: контракт)."}),
            "ground_mask": ("MASK", {"tooltip": "Опциональная маска земли/фона (Phase A: контракт)."}),
            "export_lut_cube": ("BOOLEAN", {"default": False, "tooltip": "Выдать identity .cube (Phase A)."}),
        },
    }


def _build_nuke_build_input_types() -> dict:
    """Return INPUT_TYPES schema for Nuke-style model builder."""
    return {
        "required": {
            "reference": ("IMAGE", {"tooltip": "Референс кадр (target look)."}),
            "source": ("IMAGE", {"tooltip": "Исходный кадр, относительно которого строится look-модель."}),
        },
        "optional": {
            "compute_device": (
                ["auto", "cpu", "cuda"],
                {"default": "auto", "tooltip": "Устройство вычислений: auto/cpu/cuda."},
            ),
            "working_space": (
                ["oklab", "lab"],
                {"default": "oklab", "tooltip": "Рабочее пространство fit-процесса."},
            ),
            "downscale_long_side": (
                ["as_is", "1440p", "1080p", "720p"],
                {"default": "1080p", "tooltip": "Размер fit-процесса (Phase A: контракт)."},
            ),
            "fit_global": ("BOOLEAN", {"default": True, "tooltip": "Фит глобального grade (Phase A: контракт)."}),
            "fit_tone": ("BOOLEAN", {"default": True, "tooltip": "Фит тонального профиля (Phase A: контракт)."}),
            "fit_hue_sectors": ("BOOLEAN", {"default": True, "tooltip": "Фит по hue-секторам (Phase A: контракт)."}),
            "fit_local_regions": ("BOOLEAN", {"default": True, "tooltip": "Фит локальных регионов по маскам (Phase A: контракт)."}),
            "skin_mask": ("MASK", {"tooltip": "Опциональная маска кожи."}),
            "sky_mask": ("MASK", {"tooltip": "Опциональная маска неба."}),
            "ground_mask": ("MASK", {"tooltip": "Опциональная маска земли/фона."}),
            "subject_mask": ("MASK", {"tooltip": "Опциональная маска объекта."}),
            "export_lut_cube": ("BOOLEAN", {"default": False, "tooltip": "Выдать identity .cube (Phase A)."}),
            "lut_size": ("INT", {"default": 25, "min": 17, "max": 49, "step": 2, "tooltip": "Размер экспортируемого LUT."}),
        },
    }


def _build_nuke_apply_input_types() -> dict:
    """Return INPUT_TYPES schema for Nuke-style model applier."""
    return {
        "required": {
            "image": ("IMAGE", {"tooltip": "Изображение/батч для применения look-модели."}),
            "look_model_json": ("STRING", {"tooltip": "JSON-модель из ImageLookMatchNukeBuild."}),
            "strength": (
                "FLOAT",
                {"default": 1.0, "min": 0.0, "max": 1.0, "step": 0.05, "tooltip": "Сила применения модели (0..1)."},
            ),
        },
        "optional": {
            "compute_device": (
                ["auto", "cpu", "cuda"],
                {"default": "auto", "tooltip": "Устройство вычислений: auto/cpu/cuda."},
            ),
            "temporal_stabilization": (
                "BOOLEAN",
                {"default": False, "tooltip": "Темпоральная стабилизация параметров (Phase A: контракт)."},
            ),
            "temporal_alpha": (
                "FLOAT",
                {"default": 0.8, "min": 0.0, "max": 1.0, "step": 0.05, "tooltip": "Коэффициент EMA для temporal режима."},
            ),
            "shot_change_threshold": (
                "FLOAT",
                {"default": 0.2, "min": 0.0, "max": 1.0, "step": 0.01, "tooltip": "Порог обнаружения резкого shot change."},
            ),
        },
    }


class ImageLookMatchResolve:
    """Resolve-style monolithic look-match node (Phase A contract implementation)."""

    @classmethod
    def INPUT_TYPES(cls):
        """Return ComfyUI INPUT_TYPES for resolve-style look transfer."""
        return _build_resolve_input_types()

    RETURN_TYPES = ("IMAGE", "STRING", "STRING")
    RETURN_NAMES = ("matched_image", "look_json", "cube_text")
    FUNCTION = "match"
    CATEGORY = "image/color"

    def match(
        self,
        reference,
        image,
        strength=1.0,
        compute_device="auto",
        working_space="oklab",
        downscale_long_side="1080p",
        tone_model="monotonic_spline",
        palette_model="lut3d",
        lut_size=25,
        w_exposure=1.0,
        w_tone=1.0,
        w_chroma=1.0,
        skin_protection=True,
        skin_protection_strength=0.6,
        subject_mask=None,
        sky_mask=None,
        ground_mask=None,
        export_lut_cube=False,
    ):
        """Run Phase A resolve-style look transfer (identity-safe baseline)."""
        batch_size = max(reference.shape[0], image.shape[0])
        ref_batch = _pad_batch_last(reference, batch_size)
        img_batch = _pad_batch_last(image, batch_size)

        ref_h, ref_w = ref_batch.shape[1], ref_batch.shape[2]
        ref_rgb, _ = _split_alpha(ref_batch)
        img_rgb, img_alpha = _split_alpha(img_batch)
        if img_rgb.shape[1] != ref_h or img_rgb.shape[2] != ref_w:
            img_rgb = color_match_utils.resize_images_to_size(img_rgb, ref_h, ref_w)
        if img_alpha is not None and (img_alpha.shape[1] != ref_h or img_alpha.shape[2] != ref_w):
            img_alpha = color_match_utils.resize_images_to_size(img_alpha, ref_h, ref_w)

        device, warning = _resolve_compute_device(compute_device)
        s = float(max(0.0, min(1.0, strength)))
        out_list = []
        json_list = []
        cube_list = []

        iterator = tqdm(range(batch_size), desc="LookMatch[resolve]", unit="img")
        for idx in iterator:
            check_interrupt()
            ref_t = ref_rgb[idx].detach().to(device=device).clone()
            img_t = img_rgb[idx].detach().to(device=device).clone()

            # Phase A behavior intentionally keeps transform near identity.
            corrected = img_t
            if s < 1.0:
                corrected = img_t * (1.0 - s) + corrected * s
            corrected = corrected.clamp(0.0, 1.0)

            out_t = corrected.to(device=img_rgb.device)
            if img_alpha is not None:
                out_t = torch.cat([out_t, img_alpha[idx]], dim=-1)
            out_list.append(out_t.cpu())

            mse_before = float((img_t - ref_t).square().mean().item())
            mse_after = float((corrected - ref_t).square().mean().item())

            payload = {
                "status": "ok",
                "schema_name": _LOOK_RESOLVE_SCHEMA,
                "schema_version": _SCHEMA_VERSION,
                "mode": f"look_match_resolve:{working_space}",
                "phase": "A_contract_baseline",
                "contracts": {
                    "tone_model": str(tone_model),
                    "palette_model": str(palette_model),
                    "downscale_long_side": str(downscale_long_side),
                },
                "optimization": {
                    "compute_device_requested": str(compute_device).lower(),
                    "compute_device_effective": str(device),
                    "device_warning": warning,
                    "weights": {
                        "w_exposure": float(w_exposure),
                        "w_tone": float(w_tone),
                        "w_chroma": float(w_chroma),
                        "skin_protection": bool(skin_protection),
                        "skin_protection_strength": float(skin_protection_strength),
                    },
                },
                "masks": {
                    "subject_mask": bool(subject_mask is not None),
                    "sky_mask": bool(sky_mask is not None),
                    "ground_mask": bool(ground_mask is not None),
                },
                "quality": {
                    "before": {"mse": round(mse_before, 8)},
                    "after": {"mse": round(mse_after, 8)},
                    "improvement_pct": {
                        "mse": round((mse_before - mse_after) / max(mse_before, 1e-8) * 100.0, 3),
                    },
                },
            }
            json_list.append(json.dumps(payload, ensure_ascii=True))
            cube_list.append(_identity_cube_text(lut_size) if export_lut_cube else "")

        return (torch.stack(out_list, dim=0), json_list, cube_list)


class ImageLookMatchNukeBuild:
    """Nuke-style look-model builder (Phase A schema-first implementation)."""

    @classmethod
    def INPUT_TYPES(cls):
        """Return ComfyUI INPUT_TYPES for look-model builder node."""
        return _build_nuke_build_input_types()

    RETURN_TYPES = ("STRING", "STRING")
    RETURN_NAMES = ("look_model_json", "cube_text")
    FUNCTION = "build"
    CATEGORY = "image/color"

    def build(
        self,
        reference,
        source,
        compute_device="auto",
        working_space="oklab",
        downscale_long_side="1080p",
        fit_global=True,
        fit_tone=True,
        fit_hue_sectors=True,
        fit_local_regions=True,
        skin_mask=None,
        sky_mask=None,
        ground_mask=None,
        subject_mask=None,
        export_lut_cube=False,
        lut_size=25,
    ):
        """Build and return Phase A look-model JSON contract."""
        check_interrupt()
        ref = reference[0]
        src = source[0]
        device, warning = _resolve_compute_device(compute_device)

        model = {
            "status": "ok",
            "schema_name": _LOOK_MODEL_SCHEMA,
            "schema_version": _SCHEMA_VERSION,
            "mode": f"look_model_build:{working_space}",
            "phase": "A_contract_baseline",
            "build_context": {
                "compute_device_requested": str(compute_device).lower(),
                "compute_device_effective": str(device),
                "device_warning": warning,
                "downscale_long_side": str(downscale_long_side),
                "source_size": [int(src.shape[0]), int(src.shape[1])],
                "reference_size": [int(ref.shape[0]), int(ref.shape[1])],
            },
            "fit_flags": {
                "fit_global": bool(fit_global),
                "fit_tone": bool(fit_tone),
                "fit_hue_sectors": bool(fit_hue_sectors),
                "fit_local_regions": bool(fit_local_regions),
            },
            "mask_flags": {
                "skin_mask": bool(skin_mask is not None),
                "sky_mask": bool(sky_mask is not None),
                "ground_mask": bool(ground_mask is not None),
                "subject_mask": bool(subject_mask is not None),
            },
            "transform": {
                "global_affine": {
                    "matrix": [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]],
                    "bias": [0.0, 0.0, 0.0],
                },
                "tone_profile": {"type": "identity", "params": {}},
                "hue_sectors": [],
                "local_regions": [],
            },
        }
        cube_text = _identity_cube_text(lut_size) if export_lut_cube else ""
        return (json.dumps(model, ensure_ascii=True), cube_text)


class ImageLookMatchNukeApply:
    """Nuke-style look-model applier (Phase A identity-safe behavior)."""

    @classmethod
    def INPUT_TYPES(cls):
        """Return ComfyUI INPUT_TYPES for look-model applier node."""
        return _build_nuke_apply_input_types()

    RETURN_TYPES = ("IMAGE", "STRING")
    RETURN_NAMES = ("matched_image", "apply_json")
    FUNCTION = "apply"
    CATEGORY = "image/color"

    def apply(
        self,
        image,
        look_model_json,
        strength=1.0,
        compute_device="auto",
        temporal_stabilization=False,
        temporal_alpha=0.8,
        shot_change_threshold=0.2,
    ):
        """Apply look-model JSON to input image batch."""
        model = _safe_json_loads(look_model_json)
        model_valid = model.get("schema_name") == _LOOK_MODEL_SCHEMA and int(model.get("schema_version", -1)) == _SCHEMA_VERSION

        batch_size = image.shape[0]
        img_rgb, img_alpha = _split_alpha(image)
        device, warning = _resolve_compute_device(compute_device)
        s = float(max(0.0, min(1.0, strength)))

        matrix = torch.eye(3, dtype=torch.float32, device=device)
        bias = torch.zeros(3, dtype=torch.float32, device=device)
        if model_valid:
            affine = model.get("transform", {}).get("global_affine", {})
            mat_list = affine.get("matrix")
            bias_list = affine.get("bias")
            if isinstance(mat_list, list) and len(mat_list) == 3:
                try:
                    matrix = torch.tensor(mat_list, dtype=torch.float32, device=device).reshape(3, 3)
                except Exception:
                    matrix = torch.eye(3, dtype=torch.float32, device=device)
            if isinstance(bias_list, list) and len(bias_list) == 3:
                try:
                    bias = torch.tensor(bias_list, dtype=torch.float32, device=device).reshape(3)
                except Exception:
                    bias = torch.zeros(3, dtype=torch.float32, device=device)

        out_list = []
        json_list = []
        iterator = tqdm(range(batch_size), desc="LookMatch[nuke_apply]", unit="img")
        for idx in iterator:
            check_interrupt()
            src = img_rgb[idx].detach().to(device=device).clone()
            corrected = torch.einsum("hwc,dc->hwd", src, matrix) + bias.view(1, 1, 3)
            corrected = corrected.clamp(0.0, 1.0)
            if s < 1.0:
                corrected = src * (1.0 - s) + corrected * s
            out_t = corrected.to(device=img_rgb.device)
            if img_alpha is not None:
                out_t = torch.cat([out_t, img_alpha[idx]], dim=-1)
            out_list.append(out_t.cpu())

            payload = {
                "status": "ok" if model_valid else "warning",
                "schema_name": _LOOK_APPLY_SCHEMA,
                "schema_version": _SCHEMA_VERSION,
                "mode": "look_model_apply",
                "phase": "A_contract_baseline",
                "model_loaded": bool(model_valid),
                "warning": None if model_valid else "invalid_or_missing_look_model_schema",
                "apply_context": {
                    "compute_device_requested": str(compute_device).lower(),
                    "compute_device_effective": str(device),
                    "device_warning": warning,
                    "temporal_stabilization": bool(temporal_stabilization),
                    "temporal_alpha": float(temporal_alpha),
                    "shot_change_threshold": float(shot_change_threshold),
                },
            }
            json_list.append(json.dumps(payload, ensure_ascii=True))

        return (torch.stack(out_list, dim=0), json_list)
